on : push

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              
            - name: Build the drink index.html 
              run: python build.py

            - name: Upload built files
              uses: actions/upload-pages-artifact@v3
              with: 
                path: out/

    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: build
        permissions:
            pages: write
            id-token: write
        steps:
            - name: Deploy the Drink to github pages
              uses: actions/deploy-pages@v4